# Site settings
title: A Raytracer in Rust
email: bionicle.dragon@gmail.com
description: "The adventures of a new Rust programmer, trying to build a ray-tracer, and taking you along for the ride."
baseurl: "/rust-raytracer"
url: "https://porglezomp.github.io"
twitter_username: stickfigure42
github_username:  porglezomp

# Build settings
markdown: redcarpet
permalink: pretty
